services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspaces/lash-brow-ohana:cached
    working_dir: /workspaces/lash-brow-ohana/src
    command: sleep infinity

    # devcontainer 起動時に必要なものはまとめて起動
    depends_on:
      - nginx
      - mysql
      - mailhog
      - node
      - phpmyadmin
